# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime-OVapi.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import gtfs_realtime_pb2 as gtfs__realtime__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19gtfs-realtime-OVapi.proto\x12\x10transit_realtime\x1a\x13gtfs-realtime.proto\"d\n\x13OVapiTripDescriptor\x12\x18\n\x10realtime_trip_id\x18\x01 \x01(\t\x12\x17\n\x0ftrip_short_name\x18\x02 \x01(\t\x12\x1a\n\x12\x63ommercial_mode_id\x18\x03 \x01(\t\"%\n\x14OVapiVehiclePosition\x12\r\n\x05\x64\x65lay\x18\x01 \x01(\x05\"(\n\x0fOVapiTripUpdate\x12\x15\n\rtrip_headsign\x18\x01 \x01(\t\"o\n\x13OVapiStopTimeUpdate\x12\x15\n\rstop_headsign\x18\x01 \x01(\t\x12\x17\n\x0fscheduled_track\x18\x02 \x01(\t\x12\x14\n\x0c\x61\x63tual_track\x18\x03 \x01(\t\x12\x12\n\nstation_id\x18\x04 \x01(\t\"g\n\x16OVapiVehicleDescriptor\x12\x1d\n\x15wheelchair_accessible\x18\x01 \x01(\x08\x12\x14\n\x0cvehicle_type\x18\x02 \x01(\t\x12\x18\n\x10vehicle_headsign\x18\x03 \x01(\t:f\n\x14ovapi_tripdescriptor\x12 .transit_realtime.TripDescriptor\x18\xeb\x07 \x01(\x0b\x32%.transit_realtime.OVapiTripDescriptor:j\n\x16ovapi_vehicle_position\x12!.transit_realtime.VehiclePosition\x18\xeb\x07 \x01(\x0b\x32&.transit_realtime.OVapiVehiclePosition:[\n\x11ovapi_trip_update\x12\x1c.transit_realtime.TripUpdate\x18\xeb\x07 \x01(\x0b\x32!.transit_realtime.OVapiTripUpdate:s\n\x16ovapi_stop_time_update\x12+.transit_realtime.TripUpdate.StopTimeUpdate\x18\xeb\x07 \x01(\x0b\x32%.transit_realtime.OVapiStopTimeUpdate:p\n\x18ovapi_vehicle_descriptor\x12#.transit_realtime.VehicleDescriptor\x18\xeb\x07 \x01(\x0b\x32(.transit_realtime.OVapiVehicleDescriptorB\x1d\n\x1b\x63om.google.transit.realtime')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gtfs_realtime_OVapi_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
  gtfs__realtime__pb2.TripDescriptor.RegisterExtension(ovapi_tripdescriptor)
  gtfs__realtime__pb2.VehiclePosition.RegisterExtension(ovapi_vehicle_position)
  gtfs__realtime__pb2.TripUpdate.RegisterExtension(ovapi_trip_update)
  gtfs__realtime__pb2.TripUpdate.StopTimeUpdate.RegisterExtension(ovapi_stop_time_update)
  gtfs__realtime__pb2.VehicleDescriptor.RegisterExtension(ovapi_vehicle_descriptor)

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033com.google.transit.realtime'
  _OVAPITRIPDESCRIPTOR._serialized_start=68
  _OVAPITRIPDESCRIPTOR._serialized_end=168
  _OVAPIVEHICLEPOSITION._serialized_start=170
  _OVAPIVEHICLEPOSITION._serialized_end=207
  _OVAPITRIPUPDATE._serialized_start=209
  _OVAPITRIPUPDATE._serialized_end=249
  _OVAPISTOPTIMEUPDATE._serialized_start=251
  _OVAPISTOPTIMEUPDATE._serialized_end=362
  _OVAPIVEHICLEDESCRIPTOR._serialized_start=364
  _OVAPIVEHICLEDESCRIPTOR._serialized_end=467
# @@protoc_insertion_point(module_scope)
